name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  cluster:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.KEY}}
        aws-secret-access-key: ${{ secrets.SECRET}}
        aws-region: 'us-east-1'

    - name: Deploy
      uses: aws-actions/aws-cloudformation-github-deploy@master
      with:
        name: testingworkflowNada
        template: template.yaml
        capabilities: CAPABILITY_NAMED_IAM
